### ISSUE TITLE
Talking with Calabrini bugs

### ISSUE THREAD

**Issue by Fenyx4** [plaidpants/u4-decompiled#1] opened 2023-12-13 01:34 UTC
When speaking with Calabrini in Moonglow if you ask Job he asks "Dost thou seek an inn or healing?" and you respond "Yes" he asks "Which?"

He has two keywords "Inn" and "Healing" and both of these should then be made available but only Healing is.

(Additionally if you ask "Healing" he responds with his "Health" response instead of his "HEAL" keyword response. This is a bug in the base game. I fixed that in a U4 patch by changing his dialogue to "Dost thou seek\nan inn or art\nthou injured?" and the keyword to "INJU".)

P.S. This is all really cool! Thanks for putting this together. I'm curious how you put together keywords popping up as options? Did you manually go through and add them or do it automatically somehow? Like "if keyword appears in dialogue text then show word from dialogue as an option"?

**Comment by plaidpants** [comment] 2023-12-13 02:06
I did not add the keyword stuff manually as it would have been too much work. I did it programmatically. I scan the current session text for words and build a database of currently known words. I then look for matching words contained in the character info. If there is a match I display the option when you talk to the character. Since the previous text contained the word healing and inn it should have provided it as an option, unless there is a bug. Probably a bug. I will check. I will also check out the other text issue you mentioned. Another issue is that the game only retains words in the current session so if you resume from a save it will not know the words. But this was kind of an experiment and I wanted to avoid needing a keyboard. You can type words on the PC keyboard however to get around this, I think it needs to be lowercase. Glad you enjoyed the conversion to VR. The VR rework of the dungeons to remove the 3D maze and remap everything to a tilemap is what I think it the most interesting but this word matching thing would be a close second and is similar to modern game approaches to character conversations such as morrowind and others. Thanks for playing.

**Comment by plaidpants** [comment] 2024-01-11 21:43
OK, I think I know what the problem is, the text "DOST THOU SEEK\nAN INN OR\n**HEALING**?" vs. the keyword text "**HEALER**" as these do not match, the original game only checked if the first 4 characters match but my code checks all 6 and since it also matches the talk word "HEALTH" you probably cannot get the healer response. I think your idea to reword the text to use the keyword "INJURY" is probably a good one. I will also check my code to make sure it only checks the first 4 characters. I noticed that this is not fixed in u4remasteredA2 need to contact @sean-gugler

        "description": "A TALL MAGE.", 
        "health": "FINE.", 
        "humility_question": false, 
        "job": "I BEAR GREETINGS\nFROM THE FAIR\nCITY OF\nMOONGLOW.", 
        "keyword_1": "INN", 
        "keyword_2": "HEALER", 
        "keyword_response_1": "WE HAVE AN\nEXCELLENT INN.", 
        "keyword_response_2": "OUR HEALER IS\nONE OF THE BEST!", 
        "name": "CALABRINI", 
        "pronoun": "HE", 
        "question": "DOST THOU SEEK\nAN INN OR\nHEALING?", 
        "question_no_answer": "PERHAPS, THE\nSHRINE WHICH\nLIES ON AN ISLE\nTO THE NORTH!", 
        "question_trigger": "job", 
        "question_yes_answer": "WHICH?", 
        "turns_away_prob": 0

**Comment by plaidpants** [comment] 2024-01-12 21:52
You should be able to correct this issue by using your U4 patch on the files in the "AppData\LocalLow\SwivelChairGames\ANKH-VR\u4" directory. I'm going to attempt something new but it will be a while. question, does your U4 patcher change the location of any of the data/strings in the AVATAR.EXE or other data files, I'm thinking I should include something like your patcher in my code so I can correct the original files as I load them including the EXE. I'm going to try and use the EXE for all data I currently have in my executable and replace it with offsets into the EXE and treat it as a big data file. That way I can remove any copyrightable data from this binary and avoid having to use the IPS patcher on the EXE. I can then avoid needing to dynamically patch my code from the unity engine at launch. This will allow me to port something to the Oculus quest natively. Anyway I will give it a go.

**Comment by Fenyx4** [comment] 2024-01-13 15:18
Pix's UltimaPatcher just keeps full copies of the data files and copies them over the top. See [here](https://github.com/Fenyx4/UltimaPatcher/tree/master/UltimaPatcher/Files/U4v200) for an example of the files. Nothing fancy going on. (And it is a bit concerning about copyright as more and more files get added.) 
But I am afraid some versions of the U4 update does change the locations of the data in the AVATAR.EXE.

It is updates that came from the Ultima 4 Randomizer that change the offsets as I am changing code in AVATAR.EXE and recompiling it.
If it helps I have a big list of the original offsets and another big list of the new offsets. I'm afraid that might change in the future. Sorry... >_<

https://github.com/Fenyx4/U4DosRandomizer/blob/master/U4DosRandomizer/AvatarOffsetsOriginal.cs
https://github.com/Fenyx4/U4DosRandomizer/blob/master/U4DosRandomizer/AvatarOffsetsNew.cs

**Comment by plaidpants** [comment] 2024-01-13 18:24
There are approximately 1600 references to data/strings in the AVATAR.EXE code so I'm not sure how practical it will be to adjust these if they move due to patches.

**Comment by plaidpants** [comment] 2024-01-13 19:17
OK, I've pushed my changes, 1612 AVATAR.EXE references total. oofa. This still will not fix this issue however. More to come.

**Comment by sean-gugler** [comment] 2024-01-14 01:39
> I noticed that this is not fixed in u4remasteredA2 need to contact @sean-gugler

Thanks for alerting me! I'll adopt the suggested fix from @Fenyx4

**Comment by plaidpants** [comment] 2024-01-27 23:03
BTW @Fenyx4 This issue also exists with Michelle but @sean-gugler already fixed that one.

**Comment by Fenyx4** [comment] 2024-01-28 02:29
Thanks! 

Hrm, lemme check my notes...

Looks like I've already fixed Michelle. Here's a (hopefully) complete list of things I fixed (and where I found people already fixing it); https://github.com/Fenyx4/U4DosRandomizer/blob/master/FIXES.md

Here's my code that is fixing them so you can see how I fixed it. https://github.com/Fenyx4/U4DosRandomizer/blob/6136216be99b31432228098f7322e98d6f0b3bb3/U4DosRandomizer/Talk.cs#L589-L662

**Comment by plaidpants** [comment] 2024-01-31 02:44
OK, I just released a Oculus Quest Native app, hope it doesn't have too many bugs, this issue should now be addressed, @Fenyx4, @sean-gugler

**Comment by plaidpants** [comment] 2024-01-31 03:07
fixed

**Closed as completed by plaidpants** 2024-01-31 03:07 UTC
Labels: bug
